// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw5OoWiJj_Wx336huYLqdoLSjyNpXJrR4',
    appId: '1:596905665962:web:5dafa9d4f098b2df41b7d3',
    messagingSenderId: '596905665962',
    projectId: 'ia-docente-app',
    authDomain: 'ia-docente-app.firebaseapp.com',
    storageBucket: 'ia-docente-app.firebasestorage.app',
    measurementId: 'G-LCD9GYD2Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkMpWA3cflWVWYBeD6SVSeeocP_yX1emk',
    appId: '1:596905665962:android:40f8545da381b2ba41b7d3',
    messagingSenderId: '596905665962',
    projectId: 'ia-docente-app',
    storageBucket: 'ia-docente-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkt-XkT5m9GKEAvN81xs3s2WyQXhqkVYw',
    appId: '1:596905665962:ios:aa6a3f1ded0b5ebe41b7d3',
    messagingSenderId: '596905665962',
    projectId: 'ia-docente-app',
    storageBucket: 'ia-docente-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkt-XkT5m9GKEAvN81xs3s2WyQXhqkVYw',
    appId: '1:596905665962:ios:aa6a3f1ded0b5ebe41b7d3',
    messagingSenderId: '596905665962',
    projectId: 'ia-docente-app',
    storageBucket: 'ia-docente-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw5OoWiJj_Wx336huYLqdoLSjyNpXJrR4',
    appId: '1:596905665962:web:631a3f1204583f2641b7d3',
    messagingSenderId: '596905665962',
    projectId: 'ia-docente-app',
    authDomain: 'ia-docente-app.firebaseapp.com',
    storageBucket: 'ia-docente-app.firebasestorage.app',
    measurementId: 'G-0GT29CN328',
  );
}
